### ISSUE TITLE
Documentation: show examples of good docs

### ISSUE THREAD

**Issue by danielkornev** [deepmipt/DeepPavlov#1369]
# Tasks
* [x] Review existing criterias for documentation 
* [x] Suggest own criterias
* [x] Show good examples and explain why

**Comment by oserikov** [comment]
me, i really love the minimalism of requests and beautifulsoup docs
th

**Comment by danielkornev** [comment]
# Conversational AI Libraries & Services

| Project Name                   | Project Type                    | Docs Link                                                    | Concepts | How-Do-I | Bot Examples | Context Management | Versioning & Publishing                                  | Integration | Security | Programming Languages         | Pros                                          | Cons                                                         | Rating (5-max) |
| ------------------------------ | ------------------------------- | ------------------------------------------------------------ | -------- | -------- | ------------ | ------------------ | -------------------------------------------------------- | ----------- | -------- | ----------------------------- | --------------------------------------------- | ------------------------------------------------------------ | -------------- |
| RASA                           | All-in-One                      | [Docs](https://rasa.com/docs/rasa)                           | Yes      | No       | Yes          | ?                  | Partial (model storage but no versioning, no publishing) | Yes         | No       | Python, maybe others?         | Docs are built around build AI assistant      | Home page is awful, actions docs are unclear                 | 3              |
| Microsoft LUIS                 | NLU Library                     | [Docs](https://docs.microsoft.com/en-us/azure/cognitive-services/luis/) | Yes      | Yes      |              |                    | Yes                                                      | No          | Yes      | C#, Python, Node.js, Java, Go | Comprehensive, detailed, home page is awesome | Unclear how to publish bot or how it is used w/ other parts  | 4              |
| Microsoft Power Virtual Agents | Conv AI Orchestrators + Hosting | [Docs](https://docs.microsoft.com/en-us/power-virtual-agents/fundamentals-what-is-power-virtual-agents) | Yes      |          | Yes          | None?              | Yes                                                      | Yes         | Yes      | C#, Java, JS, Python          | Comprehensive, detailed                       | A bit complicated                                            | 3              |
| Microsoft Bot Framework SDK    | Conv AI Orchestrator            | [Docs](https://docs.microsoft.com/en-us/azure/bot-service/index-bf-sdk?view=azure-bot-service-4.0) |          |          | Yes          |                    | Yes                                                      | Yes         | Yes      | C#, Java, JS, Python          | Comprehensive, detailed, home page is awesome | Unclear how it is using LUIS                                 |                |
| Amazon Lex                     | All-in-One                      | [Docs](https://docs.aws.amazon.com/lex/latest/dg/what-is.html) |          |          | Yes          | Yes                | Yes                                                      | Yes         | Yes      | None (only REST APIs)         | Comprehensive, detailed                       | SAAS only, no examples how to use individual elements outside of Conversational AI, | 3              |

**Comment by danielkornev** [comment]
# General NLP Libraries & Services

| Project Name                 | Project Type | Docs Link                                                | Concepts | How-Do-I | General Models | Domain-Specific Models | Configs | Versioning | High Performance (GPU, CPU) | Globalization                            | Programming Languages | Pros | Cons | Rating (5-max) |
| ---------------------------- | ------------ | -------------------------------------------------------- | -------- | -------- | -------------- | ---------------------- | ------- | ---------- | --------------------------- | ---------------------------------------- | --------------------- | ---- | ---- | -------------- |
| Microsoft Cognitive Services | SAAS         |                                                          |          |          |                |                        |         |            |                             |                                          |                       |      |      |                |
| Allen NLP                    | Library      |                                                          |          |          |                |                        |         |            |                             |                                          |                       |      |      |                |
| HT                           | Library      |                                                          |          |          |                |                        |         |            |                             |                                          |                       |      |      |                |
| Stanford Core NLP            | Library      | [Docs](https://stanfordnlp.github.io/CoreNLP/index.html) |          |          |                |                        |         |            |                             | Arabic, Chinese, French, German, Spanish | Java                  |      |      |                |
| Amazon Comprehend            | SAAS         | N/A                                                      |          |          |                |                        |         |            |                             |                                          |                       |      |      |                |
| Spacy                        | Library      | [Docs](https://spacy.io/usage)                           |          |          |                |                        |         |            |                             |                                          |                       |      |      |                |

**Comment by danielkornev** [comment]
Super cool examples of more modern documentation systems:
https://dev.to/nafis/5-free-static-documentation-generators-you-must-check-out-5ged

**Comment by danielkornev** [comment]
feels like this is the fastest:
https://docute.org/options

**Comment by danielkornev** [comment]
https://www.tensorflow.org/tutorials/quickstart/beginner
https://pytorch.org/tutorials/beginner/transformer_tutorial.html

**Comment by danielkornev** [comment]
![image](https://user-images.githubusercontent.com/5264043/107233754-f61e7680-6a33-11eb-89df-73fb6104fb1c.png)
Example CJM (Stages) for "Find an open-source Conversational Platform"
