### ISSUE TITLE
Models & Code Integration, Maintenance, and Deprecation Policy 

### ISSUE THREAD

**Issue by danielkornev** [deepmipt/DeepPavlov#1380]
# Problems
* Many models are very rarely used but require support (and testing during build process)
* Some models no longer have owners

# Integration
* tests etc.
* (about papers) <-- upd: we don't publish research-only models into DP Library but only good production-quality code

# Maintenance
* Each currently integrated component should have an active owner w/ responsibilities (e.g., maintain code, answer questions in forums & GH Issues etc.) 

# Deprecation
* If we want to remove something (model or class) we should provide an alternative
* For each component we want to remove, we should mark all related components that are used only by this component
* We use our usage stats to identify what should be cut
* Threshold to cut - e.g., very small to no usage in last 6 months
* If we want to keep something, we want to have its owner (and if needed a plan for its growth/improvement)

# Tasks
* [ ] Grab statistics and form a list of models w/ their usage stats, owners, new owners (if needed) - @moryshka 
* [ ] Add owners (current, new if needed) - @vaskonov @IgnatovFedor 
* [ ] Formulate a list of models for deprecation - all

**Comment by danielkornev** [comment]
1. We need full list of configs per each product feature
2. We need statistics for each config
3. We need dependencies - @danielkornev
